Create a basic footer
Paefax/paefax-language-app pull request #31
Opened 2022-10-12 19:04 UTC by FelixJacobsen

Basic footer to be continued tomorrow

2022-10-15 18:36 UTC, FelixJacobsen commented
Would need some feedback on how this looks in laptop screen size. Also we need to import and use our font.

2022-10-16 19:33 UTC, LordRekishi requested changes
Looks great in general, though not following the HiFi colors

2022-10-16 19:33 UTC, LordRekishi commented on src/components/NavFooter.vue
> +/* Import our font instead */
```suggestion
```

2022-10-16 19:33 UTC, LordRekishi commented on src/components/NavFooter.vue
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap");
I suggest putting this in the top of main.css instead since we will (probably) use this for more of the page later

2022-10-16 19:33 UTC, LordRekishi commented on src/components/NavFooter.vue
> +}
1. What's going on with these funky media queries? 
2. When I tried different sizes it seemed (for example) iPad Air in vertical mode looks a bit wonky?
3. Maybe we want the text to be further on the left on mobile?
4. We could also reduce the margin between the headers and its content on mobile?

2022-10-17 07:14 UTC, helenahalldiniths commented
This looks fine for a basic version, however I agree with Patrik that it looks quite weired during the "tablet width". Maybe we do not need all the info when on tablet/mobile? Insted of a sitemap footer we can just have a normal footer when not on desktop? Or maybe skip it for smaller screens? :)

2022-10-17 17:32 UTC, LordRekishi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Footer](https://trello.com/c/nMhD3Ieo/148-footer)

2022-10-18 08:50 UTC, LordRekishi approved these changes
Noice!

2022-10-18 08:50 UTC, merged