Pinia
Paefax/paefax-language-app pull request #9
Opened 2022-10-06 11:27 UTC by helenahalldiniths

This will add pinia to the project and a store for handling quizzes

2022-10-06 12:43 UTC, FelixJacobsen commented
Changes made with kevin

1. Added .value on a few places where a ref is used
2. Switched from 'onBeforeMounted' to 'onMounted'
3. Switched current question from being an object to null
4. Removed all data from questions since it's now being fetched.

2022-10-06 13:56 UTC, LordRekishi requested changes
Looks good, let's start with removing some logs and comments. Then I'll look again

2022-10-06 13:56 UTC, LordRekishi commented on README.md
> +npm install pinia
No needed, enough with npm install

2022-10-06 13:56 UTC, LordRekishi commented on src/views/HomeView.vue
>  const answers = ref([]);
```suggestion
import { useQuizStore } from "@/stores/quiz";

const answers = ref([]);
```

2022-10-06 13:56 UTC, LordRekishi commented on src/stores/quiz.js
> +  //Reaktiv
```suggestion
```

2022-10-06 13:56 UTC, LordRekishi commented on src/stores/quiz.js
> +    console.log("Kevins log3", newQuestions);
```suggestion
```

2022-10-06 13:56 UTC, LordRekishi commented on src/views/HomeView.vue
> +  console.log("Kevins log", currentQuestion.value);
```suggestion
```

2022-10-06 13:56 UTC, LordRekishi commented on src/views/HomeView.vue
> +    console.log("done");
```suggestion
```

2022-10-06 13:56 UTC, LordRekishi commented on src/views/HomeView.vue
> +      console.log(data);
```suggestion
```

2022-10-06 13:56 UTC, LordRekishi commented on src/views/HomeView.vue
> +      console.log("Kevins log2", quiz.getCurrentQuestion());
```suggestion
```

2022-10-07 06:47 UTC, helenahalldiniths commented
Good job Felix! I looked throught the code and I think the logging really helped me understand it! However I agree with Patrik that they should be removed before merging it into the main branch. I removed some logging and added some comments in order to keep track of what we are doing.

2022-10-07 06:48 UTC, merged